# Prob & Stats

## Distributions {#dist}

: (\#tab:dist) Common Distributions

| Type      | Name                   | Description             | Repr                     | Form                                                                                                                                                                                                                               | Expectation           | Variance                                     | CDF                                                                                      | MLE                       |
| --------- | ---------------------- | ----------------------- | ------------------------ | ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | --------------------- | -------------------------------------------- | ---------------------------------------------------------------------------------------- | ------------------------- |
| Discrete  | Geometric              | First Occur Times       | \(G(X)\)                 | \(p(x=k) = (1-p)^{k-1}p\)                                                                                                                                                                                                          | \(\frac{1}{p}\)       | \(\frac{1-p}{p^2}\)                          |                                                                                          |                           |
| Discrete  | Binomial               | Replacement Sampling    | \(B(n, p)\)              | \(p(x=k)=\binom{n}{k}p^{k}(1-p)^{n-k}\)                                                                                                                                                                                            | \(np\)                | \(np(1-p)\)                                  |                                                                                          | \(\hat{p} = \frac{x}{n}\) |
| Discrete  | Hypergeometric         | No Replacement Sampling | \(H(n, p)\)              | \(p(x=k)=\frac{\binom{M}{k}\binom{N-M}{n-k}}{\binom{N}{N}}\)                                                                                                                                                                       | \(n\frac{M}{N}\)      | \(\frac{N-n}{N-1}n\frac{M}{N}\frac{N-M}{N}\) |                                                                                          |                           |
| Discrete  | Poisson                | Occur Times             | \(P(\lambda)\)           | \(p(x=k)=\frac{\lambda^{k}e^{-\lambda}}{k!}\)                                                                                                                                                                                      | \(\lambda \)          | \(\lambda\)                                  |                                                                                          | \(\lambda = \bar{x}\)     |
| Continual | Uniform                | ---                     | \(U(a, b)\)              | \(f(x) = \begin{cases}\frac{1}{b-a} &\quad (a\le x\le b) \\ 0 &\quad (\text{otherwise})\end{cases}\)                                                                                                                               | \(\frac{a+b}{2}\)     | \(\frac{(b-a)^2}{12}\)                       |                                                                                          |                           |
| Continual | Exponential            | ---                     | \(E(\lambda)\)           | \(f(x) = \begin{cases}\lambda e^{-\lambda x} &\quad (x > 0) \\ 0 &\quad (\text{otherwise})\end{cases} \\ 2\lambda X_i \sim E(1/2) \sim \chi_{2}^{2} \\ 2\lambda(X_1+X_2+\cdots+X_n) \sim \chi_{2n}^{2} \quad X_i \sim E(\lambda)\) | \(\frac{1}{\lambda}\) | \(\frac{1}{\lambda^{2}}\)                    |                                                                                          |                           |
| Continual | Normal                 | ---                     | \(N(\mu, \sigma^{2})\)   | \(f(x) = \frac{1}{\sqrt{2\pi}\sigma^{2}}e^{-\frac{1}{2}(\frac{x-\mu}{\sigma})^2}\)                                                                                                                                                 | \(\mu\)               | \(\sigma^{2}\)                               |                                                                                          |                           |
| Continual | Chi Square             | ---                     | \(\chi_{n}^{2}\)         | \(\chi_{n}^{2} = \sum\limits_{i=1}^{n}X_{i}^{2} \\ X_i \sim N(0,1)\)                                                                                                                                                               | \(n\)                 | \(2n\)                                       |                                                                                          |                           |
| Continual | Non-Central Chi Square | ---                     | \(\chi_{n,\lambda}^{2}\) | \(\chi_{n, \lambda}^{2} = \sum\limits_{i=1}^{n}X_{i}^{2} \\ X_i \sim N(\mu_{i},1) \\ \lambda=\sum\mu_{i}^2\)                                                                                                                       | \(n + \lambda\)       | \(2n + 4\lambda\)                            |                                                                                          |                           |
| Continual | T Distribution         | ---                     | \(t_{n}\)                | \(t_{n}=\frac{X}{\sqrt{\chi_{n}^2/n}} \quad X\sim N(0,1)\)                                                                                                                                                                         |                       |                                              |                                                                                          |                           |
| Continual | Non-Central T          | ---                     | \(t_{n, \delta}\)        | \(t_{n, \delta}=\frac{Z + \delta}{\sqrt{\chi_{n}^2/n}} \\ P(t_{n, \delta_1} \le X) \ge P(t_{n, \delta_2} \le X) \quad \delta_1 \le \delta_2 \)                                                                                     |                       |                                              |                                                                                          |                           |
| Continual | F Distribution         | ---                     | \(F_{n,m}\)              | \(F_{n, m} = \frac{{\chi_{n}^{2}\;/n}}{\chi_{m}^{2}\;/m} \\ F_{1, n} = t_{n}^{2}\)                                                                                                                                                 |                       |                                              |                                                                                          |                           |
| Continual | Non-Center F           | ---                     | \(F_{n,m, \lambda}\)     | \(F_{n, m, \lambda} = \frac{{\chi_{n, \lambda}^{2}\;/n}}{\chi_{m}^{2}\;/m}\)                                                                                                                                                       |                       |                                              |                                                                                          |                           |
| Continual | Cauchy                 | ---                     | \(C(x_0,\lambda)\)       | \(f(x; x_0, \lambda) = \frac {1} {\pi\lambda \left[1+\left(\frac {x-x_0}{\lambda}\;\right)^2\right]} = \frac{1}{\pi}\left[\frac {\lambda} {(x-x_0)^2 + \lambda^2}\right] \\ f(x; 0, 1) = \frac {1} {\pi(1+x^2)}\)                  | \(\infty\)            | \(\infty\)                                   | \(F(x; x_0, \lambda) = \frac {1}{\pi}\arctan (\frac {x - x_0}{\lambda}) + \frac {1}{2}\) |                           |
| Continual | Weibull                | ---                     | \(W(\lambda, \theta)\)   | \(f(x; \lambda, \theta) = \begin{cases}\frac {\lambda y^{\lambda - 1}}{\theta^\lambda}\exp(-(\frac {y} {\theta})^\lambda) &\quad (x > 0) \\ 0 &\quad (\text{otherwise})\end{cases} \\ W(1, \theta) \sim E(1/\theta) \)             |                       |                                              |                                                                                          |                           |

## Properties

### Exponential Distribution

If the distribution satisfies:

$$
\lim_{h \to 0}P(x \le X \le x + h | X \gt x) / h = \lambda \\
$$

Then, the distribution can be inferred as follows:

$$
\begin{align*}
&F'(x) / (1 - F(x)) = \lambda \Rightarrow F(x) = 1 - Ce^{-\lambda x} \\
&F(0) = 0 \Rightarrow C = 1 \Rightarrow F(x) = 1 - e^{-\lambda x} \\
&E(\lambda) = F'(x) = \lambda e^{-\lambda x}
\end{align*}
$$

### Weibull Distribution

In Weibull distribution, \(\lambda\) controls function shapes, and \(\theta\) controls scales. Similar to exponential distribution, it can be inferred from the condition:

$$
\begin{align*}
&F'(x) / (1 - F(x)) = \lambda x^m  \quad (m > 0)\\
&F(x) = 1 - Ce^{-\frac {\lambda}{m + 1} x^{m + 1}} \quad (C = 1)
\end{align*}
$$
