# Linear Regression

Assumptions
Errors have zero mean and constant variance 
Errors have normal distribution
Errors are unrelated to predictors
Response variable is a linear function of predictors
1. Normal probability plot can assess normality. In the plot the points should lie on or near a
    straight line, otherwise indicating a departure from this distribution.

2. Standardized residuals can assess unusual values and test independency and variance.
    It can be plotted against each of the explanatory variables that are included in the model, 
    and plotted against the ﬁtted values \(\hat y_i\) to test whether they have  constant 
    variance (homoscedasticity).

Estimation
1. OLS
$$
\begin{align*}
&\min_{\beta} ||X\beta - y||_2^2 \quad \beta = (\beta_0, \beta_1,  ..., \beta_p) \\
\hat \beta &= (X^TX)^{-1}X^Ty \\
\hat {\sigma^2} &= \frac {1} {n - p - 1} \sum_{i = 1}^{n}(y_i - \hat y_i)^2 \quad \text{ unbiased} \\
E(\hat \beta) &= \beta \\
\operatorname{Var}(\hat \beta) &=\sigma^2(X^TX)^{-1}
\end{align*}
$$
2. MLE
$$
\hat \beta = (X^TX)^{-1}X^Ty \\
\hat \sigma^2 = \frac {1} {n} \sum_{i = 1}^{n}(y_i - \hat y_i)^2 = \frac {1} {n} \sum_{i = 1}^{n}\epsilon_i^2 \quad \text{ biased}\\
E(\hat \beta) = \beta \\
\operatorname{Var}(\hat \beta) =\sigma^2(X^TX)^{-1} \\
\operatorname{Var}(\hat {\sigma^2}) = \frac {2\sigma^4} {n}
$$
Evaluation
1. R Square Score (Coefficient of determination)
$$
R^{2}(y, \hat{y}) = 1 - \frac{\sum_{i=1}^{n}(y_i - \hat{y_i})^2}{\sum_{i=1}^{n}(y_i - \bar{y})^2} \\
\bar{y} = \frac{1}{n}\sum_{i=1}^{n}y_i
$$
