# Symbols

References:

1. [LaTeX/Mathematics](https://en.wikibooks.org/wiki/LaTeX/Mathematics)

## Mathjax

Delimiters

* block mode between `$$`
* inline mode between `\(` and `\)` or between `\[` and `\]`
* text between `$` in `\text{}`

Texts

1. `{}`: group elements
1. `\, \; \quad \qquad`: narrow and wide spaces
1. \(\text{hello, world}\) <=> `\text{hello, world}`
1. `\`: escaping
1. `\backslash`: backslash itself
1. `\\`: new line
1. `\\[2ex]`: larger vertical space

Fonts

1. \(\mathbf{boldface: abcrstxyzABCDEFGHIJKLMNOPQRSTUVWXYZ}\) <=> `\mathbf`
1. \(\mathit{italic: abcrstxyzABCDEFGHIJKLMNOPQRSTUVWXYZ}\) <=> `\mathit`
1. \(\mathrm{roman: abcrstxyzABCDEFGHIJKLMNOPQRSTUVWXYZ}\) <=> `\mathrm`
1. \(\mathcal{calligraphy: abcrstxyzABCDEFGHIJKLMNOPQRSTUVWXYZ}\) <=> `\mathcal`
1. \(\mathbb{blackboard bold: abcrstxyzABCDEFGHIJKLMNOPQRSTUVWXYZ}\) <=> `\mathbb`

Special characters:

1. \(\LaTeX\) <=> `\LaTeX`
1. \(l, \ell\) <=> `l, \ell`
1. \(\because, \therefore\) <=> `\because, \therefore`
1. \(\forall, \exists\) <=> `\forall, \exists`
1. \(\angle, \prec\) <=> `\angle, \prec`
1. \(\star, \ast\) <=> `\star, \ast`
1. \(\circ, \bullet, \odot\) <=> `\circ, \bullet, \odot`
1. \(\dot{x}, \ddot{x}, \dddot{x}\) <=> `\dot{x}, \ddot{x}, \dddot{x}`
1. \(\cdot, \cdots\) <=> `\cdot, \cdots`
1. \(\bar{x}, \hat{x}, \widehat{xy}\) <=> `\bar{x}, \hat{x}, \widehat{xy}`
1. \(\overline{xyz}, \underline{xyz}\) <=> `\overline{xyz}, \underline{xyz}`
1. \(\vec{a}, \overrightarrow{abcd}\) <=> `\vec{a}, \overrightarrow{abcd}`
1. \(\overbrace{x+y}, \underbrace{x+y}\) <=> `\overbrace{x+y}, \underbrace{x+y}`
1. \(\stackrel{\text{def}}{=}\) <=> `\stackrel{\text{def}}{=}`
1. \(\top, \bot\) <=> `\top, \bot`
1. \(\vdash, \Vdash\) <=> `\vdash, \Vdash`
1. \(\oplus, \bigoplus, \otimes, \bigotimes\) <=> `\oplus, \bigoplus, \otimes, \bigotimes`

Brackets

1. \((, )\) <=> `() \left(, \right), \big[bigg, Big, Bigg](, \big[bigg, Big, Bigg])`
1. \([, ]\) <=> `[], left[, \right]`
1. \(\{, \}\) <=> `\{, \}`
1. \(\langle, \rangle\) <=> `\langle, \rangle`
1. \(\lceil, \rceil\) <=> `\lceil, \rceil`
1. \(\lfloor, \rfloor\) <=> `\lfloor, \rfloor`
1. \(\lvert, \rvert\) <=> `\lvert, \rvert`
1. \(\lVert, \rVert\) <=> `\lVert, \rVert`

Arrows

1. \(\mapsto\) <=> `\mapsto`
1. \(\to, \leftarrow, \rightarrow, \uparrow, \downarrow\) <=> `\to, \leftarrow, \rightarrow, \uparrow, \downarrow`
1. \(\Leftarrow, \Rightarrow, \Uparrow, \Downarrow\) <=> `\Leftarrow, \RightArrow, \Uparrow, \Downarrow`
1. \(\leftrightarrow, \Leftrightarrow, \iff\) <=> `\leftrightarrow, \Leftrightarrow, \iff`

basic Operators

1. `_, ^`: subscript and superscript
1. \(+, -, \times, \div, \pm, \mp\) <=> `+, -, \times, \div, \pm, \mp`
1. \(\lt, \gt, \le, \ge, \neg, =\) <=> `\lt, \gt, \le, \gt, \neg, =`
1. \(\frac{a}{b}\) <=> `\frac{a}{b} or a \over b`
1. \(\sim, \simeq, \cong\) <=> `\sim, \simeq, \cong`
1. \(\propto, \approx, \equiv\) <=> `\propto, \approx, \equiv`

Sets

1. \(\emptyset, \varnothing\) <=> `\emptyset, \varnothing`
1. \(\in, \notin\) <=> `\in, \notin`
1. \(\cap, \cup, \setminus\) <=> `\cap, \cup, \setminus`
1. \(\subset, \subseteq, \subsetneq\) <=> `\subset, \subseteq, \subsetneq`
1. \(\supset \supseteq, \subsetneq\) <=> `\supset, \supseteq, \supsetneq`
1. \(\land, \lor, \lnot\) <=> `\land, \lor, \lnot`

Functions

1. \(x^n\) <=> `x^n`
1. \(\sqrt{x}, \sqrt[4]{x}\) <=> `\sqrt{x}, \sqrt[4]{x}`
1. \(a^x\) <=> `a^x`
1. \(\log{x}, \ln{x}\) <=> `\log{x}, \ln{x}`
1. \(\sin{x}\) <=> `\sin{x}`
1. \(\cos{x}\) <=> `\cos{x}`
1. \(\tan{x}\) <=> `\tan{x}`
1. \(\cot{x}\) <=> `\cot{x}`
1. \(\sec{x}\) <=> `\sec{x}`
1. \(\csc{x}\) <=> `\csc{x}`
1. \(\arcsin{x}\) <=> `\arcsin{x}`
1. \(\arccos{x}\) <=> `\arccos{x}`
1. \(\arctan{x}\) <=> `\arctan{x}`
1. \(\mathrm{arccot\,x, arcsec\,x, arccsc\,x}\) <=> `\mathrm{arccot\,x, arcsec\,x, arccsc\,x}`
1. \(\max{x}, \min{x}, \sup{x}, \inf{x}\) <=> `\max{x}, \min{x}, \sup{x}, \inf{x}`
1. \(\text{non-standard name: }\operatorname{foo}(x)\) <=> `\operatorname{foo}(x)`

Calcs

1. \(\binom{n+1}{2k}\) <=> `\binom{n+1}{2k} or {n+1} \choose {2k}`
1. \(\sum_{i=1}^{n}, \sum\limits_{i=1}^{n}, \sum\limits_{\substack{i \le m \\ j \le n}}\) <=> `\sum_{i=1}^{n}, \sum\limits_{i=1}^{n}, \sum\limits_{\substack{i \le m \\ j \le n}}`
1. \(\prod\limits_{i=1}^{n}\) <=> `\prod\limits_{i=1}^{n}`
1. \(\infty, \lim, \varliminf, \varlimsup\) <=> `\infty, \lim, \varliminf, \varlimsup`
1. \(\mathrm{d}x, \partial, \frac{\partial f}{\partial x}, \nabla\) <=> `\mathrm{d}x, \partial, \frac{\partial f}{\partial x}, \nabla`
1. \(\int, \iint, \iiint, \idotsint, \oint\) <=> `\int, \iint, \iiint, \idotsint, \oint`

Table

1. `\begin{array}{l|cr} ... \end{array}`: table block and specify alighment and vertical line
1. `l, c, r`: left, center and right alignment
1. `|`: vertical line
1. `&, \\`: element separator and new line
1. `\hline, \hdashline` - horizontal line and horizontal dash line

```latex
$$
\begin{array}{l|cr}
\hline
Left & Center & Right \\
\hline
a1 & a2 & a3 \\
\hdashline
b1 & b2 & b3 \\
\hline
\end{array}
$$
```

$$
\begin{array}{l|cr}
\hline
Left & Center & Right \\
\hline
a1 & a2 & a3 \\
\hdashline
b1 & b2 & b3 \\
\hline
\end{array}
$$

Matrix

Similar to table, except:

1. `\begin{pmatrix} ... \end{pmatrix}`
1. `{smallmatrix}, {matrix}, {pmatrix}, {bmatrix}, {Bmatrix}, {vmatrix}, {Vmatrix}`
1. \(\cdots, \ddots, \vdots, \ldots\) <=> `\cdots, \ddots, \vdots, \ldots`

```latex
$$
\begin{pmatrix}
1 & a_1 & a_1^2 & \cdots & a_1^n \\
1 & a_2 & a_2^2 & \cdots & a_2^n \\
\vdots & \vdots & \ddots & \vdots & \vdots \\
1 & a_n & a_n^2 & \cdots & a_n^n \\
\end{pmatrix}
$$
```

$$
\begin{pmatrix}
1 & a_1 & a_1^2 & \cdots & a_1^n \\
1 & a_2 & a_2^2 & \cdots & a_2^n \\
\vdots & \vdots & \ddots & \vdots & \vdots \\
1 & a_n & a_n^2 & \cdots & a_n^n \\
\end{pmatrix}
$$

Cases

Simllar to table, except:

1. `\begin{cases} ... \end{cases}`

```latex
$$
f(n) = 
\begin{cases}
\frac{n}{2} & \text{if $n$ is even} \\
3n+1 & \text{if $n$ is odd}
\end{cases}
$$
```

$$
f(n) = 
\begin{cases}
\frac{n}{2} & \text{if n is even} \\
3n+1 & \text{if n is odd}
\end{cases}
$$

Multiline Equations

Similar to table, except:

1. `\begin{equation} ... \end{equation}`: one equation with line separation
1. `\begin{split} ... \end{split}`: one eqution with line separtion and alignment using `&`
1. `\begin{align*} ... \end{align*}`: multiple equations with line separtion and alignment, `{align}` prints line number, and `{align*}` without number

```latex
$$
\begin{split}
H(Y|X) &= \sum_{x \in X}p(x)H(Y|x) \\
&=- \sum_{x \in X}p(x)\sum_{y \in Y}p(y|x)\log{p(y|x)} \\
&=-\sum_{x \in X}\sum_{y \in Y}p(y, x)\log{p(y|x)}
\end{split}
$$
```

$$
\begin{split}
H(Y|X) &= \sum_{x \in X}p(x)H(Y|x) \\
&=- \sum_{x \in X}p(x)\sum_{y \in Y}p(y|x)\log{p(y|x)} \\
&=-\sum_{x \in X}\sum_{y \in Y}p(y, x)\log{p(y|x)}
\end{split}
$$

Styles

1. \(\color{red}{xy}\) <=> `\color{red}{xy}`
1. \(\bbox[yellow]{xy}\) <=> `\bbox[yellow]{xy}`
1. \(\bbox[yellow, 5px, border:2px solid red]{xy}\) <=> `\bbox[yellow, 5px, border:2px solid red]{xy}`

Greeks

1. \(A, \alpha\) <=> `A, \alpha`
1. \(B, \beta\) <=> `B, \beta`
1. \(\Gamma, \gamma\) <=> `\Gamma, \gamma\`
1. \(\Delta, \delta\) <=> `\Delta, \delta`
1. \(E, \epsilon\) <=> `E, \epsilon`
1. \(Z, \zeta\) <=> `Z, \zeta`
1. \(H, \eta\) <=> `H, \eta`
1. \(\Theta, \theta\) <=> `\Theta, \theta`
1. \(I, \iota\) <=> `I, \iota`
1. \(K, \kappa\) <=> `K, \kappa`
1. \(\Lambda, \lambda\) => `\Lambda, \lambda`
1. \(M, \mu\) => `M, \mu`
1. \(N, \nu\) => `N, \nu`
1. \(\Xi, \xi\) <=> `\Xi, \xi`
1. \(O, \omicron\) <=> `O, \omicron`
1. \(\Pi, \pi\) <=> `\Pi, \pi`
1. \(R, \rho\) <=> `R, \rho`
1. \(\Sigma, \sigma\) <=> `\Sigma, \sigma`
1. \(T, \tau\) <=> `T, \tau`
1. \(\Upsilon, \upsilon\) <=> `\Upsilon, \upsilon`
1. \(\Phi, \phi\) <=> `\Phi, \phi`
1. \(X, \chi\) <=> `X, \chi`
1. \(\Psi, \psi\) <=> `\Psi, \psi`
1. \(\Omega, \omega\) <=> `\Omega, \omega`

## Analysis

1. \(\mathbb{R}, \mathbb{R}^n\): real number space using `\mathbb{R}`
1. \(\max\limits_{x \in \mathbb{R}}f(x), \min\limits_{x \in \mathbb{R}}f(x)\)
1. \(\sup\limits_{x \in \mathbb{R}}f(x), \inf\limits_{x \in \mathbb{R}}f(x)\)
1. \(\lim\limits_{x \to a}f(x), \lim\limits_{x \to a^{\pm}}f(x)\)
1. \(\lim\limits_{x \to \infty}f(x), \lim\limits_{x \to \pm\infty}f(x)\)
1. \(g(x)=O(f(x)) \Leftrightarrow \sup\limits_{x \to \infty} |\frac{g(x)}{f(x)}|=A\)
1. \(g(x)=o(f(x)) \Leftrightarrow \lim\limits_{x \to \infty} \frac{g(x)}{f(x)}=0\)
1. \(f'(x), f''(x), f^{k}(x)\): kth order derivative
1. \(\frac{\partial{f}}{\partial{x}}, \frac{\partial^{2}f}{\partial{x^2}}, \frac{\partial^{k}f}{\partial{x^k}}\): kth order partial derivative
1. \(\int_{a}^{b}f(x)\mathrm{d}x, \int_{c}^{d}\int_{a}^{d}f(x,y)\mathrm{d}x\mathrm{d}y\)

## Algebra

1. uppercase and blackboard bold for vector space: \(\mathbb{R, S, T}, \mathbb{R}^n, \mathbb{R}^{m \times n}\)
1. lowercase for scalar values: \(a, b, c\)
1. lowercase and bold-face for vectors, and all vectors assumed to be column: \(\mathbf{a, b, c}\)
1. uppercase and bold-face for matrix: \(\mathbf{A, B, C}\)
1. uppercase T for transpose: \(\mathbf{x}^T\)
1. \(\mathbf{I}, \mathbf{I}_{M}\): an identity matrix with \(m \times m\) dimension

## Prob and Stats

1. uppercase for random variables: \(X,Y, Z\)
1. lowercase for samples: \(x, y, z\)
1. lowercase Greeks for parameters: \(\alpha, \beta, \gamma\)
1. random error: \(e \text{ or } \epsilon\)
1. hat lowercase Greeks for estimated parameters: \(\hat{\alpha}, \hat{\beta}, \hat{\gamma}\)
1. random variable vector: \(\left(\substack{Y_1 \\ \vdots \\Y_n}\right)\)
1. sample vector: \(\left(\substack{y_1 \\ \vdots \\y_n}\right)\)
1. distribution: \(f(y; \theta)\)
1. expectation: \(\mu = E(Y)\)
1. variance: \(\sigma^2 = D(Y) = \mathrm{Var}(Y)\)
1. covariance: \(\mathrm{Cov}(X,Y) = E(X-E(X))(Y-E(Y))\) 
1. correlation coefficient: \(\rho_{XY} = \frac{\mathrm{Cov}(X,Y)}{\sqrt{D(X)}\sqrt{D(Y)}}\)
