# Django

1. Installation
    1. django
        1. `pip install django==4.0`
        2. `django.get_version()`
    2. mysqlclient: for MySQL
2. commands
    1. create project: `django-admin startproject mysite [.]`
    4. create app: `python manage.py startapp polls`
    5. run server: `python manage.py runserver [8000, 0:8080]`
    6. generate model from existing table: `python manage.py inspectdb table_name --database=db
    7. django shell: `python manage.py shell`
    8. create superuser: `python manage.py createsuperuser`
    9. collect static files: `python manage.py collectstatic`
3. deployment
    1. nginx
        1. static file

            ```
            location ^~ STATIC_URL_VALUE (/static/, e.g){
            alias STATIC_ROOT_DIR (/data/static/, e.g);
            }
            ```
        2. media

            ```
            location ^~ MEDIA_URL_VALUE (/media/, e.g) {
            internal # may need
            alias MEDIA_ROOT_DIR (/data/html/media/, e.g);
            }
            ```
4. Structure
    1. project
        1. `mysite/`
            1. `manage.py`
            2. `templates/`: created manually
                1. `admin/`
                    1. `base_site.html`
                        1. copy from `django\contrib\admin\templates\admin\base_site.html`
                        2. modify brand block name
                        3. add `DIRS` in `TEMPLATES: {"DIRS": [BASE_DIR / 'templates', ]}` of `settings`
            3. `mysite/`
                1. `__init__.py`
                2. `urls.py`
                    1. `admin.site.site_header = "Data Management"`: change `Django administration` text which appears on the login page and the admin site, can also do this by overwriting `base_site.html` branding block
                    2. `admin.site.site_title = "Data Management`
                    3. `admin.site.index_title = "Application"`
                    4. `admin.site.site_url = None`: cancel `view site` when the value is `""` or `None`
                        1. `None` or `""`: cancel `view site`
                        2. `/admin`: direct to other url
                3. `settings.py`
                    1. `LANGUAGE_CODE = "zh-Hans"`
                    2. `TIME_ZONE = "Asia/Shanghai"` and `USE_TZ = False`
                    3. `ALLOWED_HOSTS=["*", ]`
                    4. `DEBUG = False`
                    5. `STATICFILES_DIRS = [BASE_DIR / "static", ]`: created manually include specified static directories
                    6. `STATIC_ROOT = BASE_DIR / "staticfiles"`: destination directory for packaging all static files when using `python manage.py collectstatic`
                    7. `LOCALE_PATHS = [BASE_DIR / "locale"]`: created manually for locale files
                        1. `python manage.py makemessages -l zh_hans`: create chinese language `po` file
                        2. `python manage.py compilemessages`: compile to `mo` file
                        3. gettext
                            1. [download for windows](https://mlocati.github.io/articles/gettext-iconv-windows.html)
                    8. Databases
                        1. mysqlclient for MySQL

                        ```python
                        DATABASES = {
                            # SQLite
                            'default': {
                                'ENGINE': 'django.db.backends.sqlite3',
                                'NAME': BASE_DIR / 'db.sqlite3',
                            },
                            # MySQL
                            'default': {
                                'ENGINE': 'django.db.backends.mysql',
                                'NAME': 'django',
                                'USER': 'django',
                                'PASSWORD': 'django',
                                'HOST': 'localhost',
                                'PORT': 3306
                            },
                        }
                        ```
                4. `wsgi.py`
                5. `asgi.py`
    2. app
        1. install apps
            1. add: `polls.apps.PollsConfig`
            2. update models: `python manage.py makemigrations polls`
            3. print updated sql: `python manage.py sqlmigrate polls 0001`
            4. check without make migrations: `python manage.py check`
            5. make an update to database: `python manage.py migrate rolls`
        2. structure
            1. `polls/`
                1. `__init__.py`
                2. `admin.py`
                    1. `class ChoiceInline(admin.TabularInline)`
                        1. `model = Choice`
                        2. `extra = 3`
                    2. `class QuestionAdmin(admin.ModelAdmin)`
                        1. `fields = ["pub_date", "question_text"]`: fields on the edit form
                        2. fieldsets: group fields

                            ```python
                            fieldsets = [
                                (None, {"fields": ["question_text",]}),
                                ("Date information", {"fields": ["pub_date", ]}),
                            ]
                            ```
                        3. `inlines = [ChoiceInline, ]`
                        4. `list_display = ("question_text", "pub_date")`: display a tuple of field names
                        5. `list_filter = ["pub_date", ]`
                        6. `search_fields = ["question_text",]`
                        7. `list_per_page = 10`
                    3. `admin.site.register(Question, [QuestionAdmin])` or `@admin.register(Question)`
                3. `apps.py`
                    1. `class PollsConfig(AppConfig)`
                        1. `name="polls"`
                        2. `verbose_name="verbose polls"`
                4. `migrations/`
                    1. `__init__.py`
                5. `models.py`
                    1. `*Field`
                        1. `verbose_name`: column name shows on admin page
                        2. `@admin.display(description="")`: decorate generated column
                    2. `class Meta`:
                        1. `verbose_name`
                        2. `verbose_name_plural`
                        3. `app_label="myapp"`
                        4. `db_table = "table_name"`
                        5. `ordering = ('id',)`
                    3. special fields
                        1. `DateTimeField`
                            1. `auto_now_add=True`: set when the instance is created
                            2. `auto_now=True`: update everytime when `save` method is called
                6. `views.py`
                7. `tests.py`
                    1. test: `python manage.py test polls`
                8. `urls.py`: created manually
                    1. `app_name = "polls"`: add namespaces to URLconf, can be used in template url tag
                9. `forms.py`: created manually
                10. `templates/`: created manually
                    1. `polls/`: create template file in this directory
                11. `static/`: created manually
                    1. `polls/`: create static files in this directory
5. Templates
    1. comments
        1. single line: `{# ... #}`
        2. multiple lines: `{% comment "Optional note" %} ... {% endcomment %}`
    2. variables: surrounded by `{{ }}`
        1. `{{ question }}`
        2. `{{ dict.id }}`: dict's key value
        3. `{{ object.id }}`: object attribute value
        4. `{{ list.0 }}`: list index value
    3. tags: surrounded by `{% %}`
        1. url: `{% url 'polls:detail' arg1 arg2 %}`
        2. static file: css, js, images

            ```
            {% load static %}
            {% static 'polls/style.css' %}
            ```
        3. csrf: `{% csrf_token %}` for post form

            ```html
            <form method="post">
            {% csrf_token %}
            ...
            </form>
            ```
        4. if

            ```html
            {% if condition %}
                ...
            {% elif condition %}
                ...
            {% else %}
                ...
            {% endif %}`
            ```
        5. for
            1. `{{ forloop.counter }}`: times the `for` tag through its loop

            ```
            {% for item in items %}
                ...
            {% endfor %}`
            ```
    4. filters: transform variable values and tag argument
        1. `{{ django|titile }}`
        2. `{{ ... | pluralize }}`
        3. `{{ my_date|date: "Y-m-d" }}`
    5. blocks
        1. `{% extends "base.html" %}`
        2. `{% block block_name %}{% endblock %}`
6. Object
    1. request
        1. `HttpRequest`
            1. `request.POST["choice"]`: raise `KeyError` if data not provided in POST data
    2. response
        1. `HttpResponse`
        2. `Http404`
        3. `HttpResponseRedirect`
            1. should always return an `HttpResponseRedirect` after successfully dealing with POST data
            2. couple with `reverse` method
    3. generic views
        1. `template_name`
        2. `model`
        3. `context_object_name`
        4. `get_queryset(self)`
7. Applications
    1. [django-admin-tools](https://django-admin-tools.readthedocs.io/en/latest/index.html)
        1. `pip install django-admin-tools==0.9.2`
        2. `urls.py`: `path("admin_tools/", include("admin_tools.urls"))`
        3. `settings.py`
            1. theme: `ADMIN_TOOLS_THEMING_CSS = 'css/theming.css'`, from `admin_tools/css/theming.css`: comment out `#header #branding h1`
            2. menu: `ADMIN_TOOLS_MENU = "menu.CustomMenu"`, use `python manage.py custommenu menu.py` to create custom menu
            3. index dashboard: `ADMIN_TOOLS_INDEX_DASHBOARD  = "customdashboard.CustomIndexDashboard"`
                1. `columns = 1`
            4. app index dashboard: `ADMIN_TOOLS_APP_INDEX_DASHBOARD = "customdashboard.CustomAppIndexDashboard"`
            5. `INSTALLED_APPS`

                ```python
                INSTALLED_APPS = [
                "admin_tools",
                "admin_tools.theming",
                "admin_tools.menu",
                "admin_tools.dashboard",
                ...
                ]
                ```
            6. `TEMPLATES`
                1. comment out `'APP_DIRS': True`
                2. add `loaders` to `OPTIONS` dict

                    ```python
                    TEMPLATES = [
                        {
                            'BACKEND': 'django.template.backends.django.DjangoTemplates',
                            'DIRS': [],
                            # 'APP_DIRS': True,
                            'OPTIONS': {
                                'context_processors': [
                                    'django.template.context_processors.debug',
                                    'django.template.context_processors.request',
                                    'django.contrib.auth.context_processors.auth',
                                    'django.contrib.messages.context_processors.messages',
                                ],
                                "loaders": [
                                    'admin_tools.template_loaders.Loader',
                                    'django.template.loaders.app_directories.Loader',
                                    'django.template.loaders.filesystem.Loader'
                                ]
                            },
                        },
                    ]
                    ```
        4. `python manage.py migrate`
    2.  django-grappelli
        1. `pip install django-grappelli==3.0.3`
        2. `urls.py`: `urlpatterns = [path("grappelli/", include("grappelli.urls")), ...]`
        3. `settings.py`
            1. `INSTALLED_APPS = ("grappelli", "django.contrib.admin", ...)`
            2. `GRAPPELLI_ADMIN_TITLE = ""`
    3. django-jazzmin
        1. `pip install django-jazzmin`
        2. `settings.py`
            1. `INSTALLED_APPS = ("jazzmin", "django.contrib.admin", ...)`
            2. JAZZMIN_SETTINGS

                ```python
                JAZZMIN_SETTINGS = {
                    # "site_logo": "conf/image/jr.png",
                    "site_logo": None,
                    "welcome_sign": "welcome here",
                    "changeform_format": "single",
                    "topmenu_links": [
                        {"name": "index",  "url": "admin:index", "permissions": ["auth.view_user"]},
                        {"name": "platform", "children": [
                            {"name": "scheduler", "url": "http://192.168.229.128:8080/", "new_window": True},
                        ]
                        },
                    ],
                }
                ```
            3. JAZZMIN_UI_TWEAKS
                ```python
                JAZZMIN_UI_TWEAKS = {
                "theme": "simplex",
                }       
                ```
        3. `utils.py`
            1. `make_menu`: update `url` in link to `name` in link

                ```python
                # Url links
                if "url" in link:
                    menu.append(
                        {
                            "name": link.get("name", "unspecified"),
                            "url": get_custom_url(link["url"], admin_site=admin_site),
                            "children": None,
                            "new_window": link.get("new_window", False),
                            "icon": link.get("icon", options["default_icon_children"]),
                        }
                    )
                
                if "name" in link:
                    menu.append(
                        {
                            "name": link.get("name", "unspecified"),
                            "url": link.get("url", "#"),
                            "children": link.get("children", None),
                            "new_window": link.get("new_window", False),
                            "icon": link.get("icon", options["default_icon_children"]),
                        }
                    )
                ```
        4. `registration/logged_out.html` file
            1. `Thanks for spending some quality time with the Web site today.`: `Web` to lower `web` for i18n
