# JavaScript

JS (JavaScript) is used to make web page dynamic.

References:

1. [JavaScript prototype](https://www.cnblogs.com/dolphinX/p/3286177.html)
2. [Learn ES2015](https://babeljs.io/docs/en/learn)

## Syntax

### Basic {-}

1. Comments
    1. `//`
    2. `/* ... */`
2. Name Rules
    1. `a-zA-Z0-9_` are valid characters
    2. do not start with `_` and numbers
    3. lower camel case convention
3. Declarations
    1. `var`: need not initialization (`undefined`), scope to function and the value can be changed
    2. `let`: similar to `var`, but scope to block `{}` and cannot be declared multiple times
    3. `const`: need initialization, scope to block. the value cannot be modified, attributes can
4. Data Types
    1. String: `let myVariabe = "abc"`
        1. Escaping: `\' \" \\ \b \t \n \v \f \r \xXX \uXXXX`
        2. attributes and methods:
            1. `.length`
            2. `str[i]`
            3. `.indexOf() - return -1 when not found`
            4. `.slice()`
            5. `.toLowerCase()`
            6. `.toUpperCase()`
            7. `.replace()`
            8. `.split()`
    2. Number: `let myVariable = 10`. It has the following methods:
        1. `.toFixed()`
        2. `.toString()`
        3. `Number()`
    3. Boolean: `[true, false]`, the following values will be evalated as `false` in braches and loops construction
        1. `false`
        2. `0`
        3. `""`
        4. `null`
        5. `NaN`
        6. `undefined`
    4. NULL: a zero object, value has nothing, `let myVariable = null`
        1. `Number(null) === 0`
    5. NaN: Not a Number
    6. undefined
        1. when variable has not been initialized
        2. when function parameter is not provided
        3. when the function has no return value
        4. when object has not the given attribute
        5. `Number(undefind)` returns `NaN` default
    7. Array: zero-indexed, `let myVariable = ["Bob", "Alan"]; myVariable[1] == "Alan"`
        1. `.join()`
        2. `.reverse()`
        3. `.push()`: add element to the end of an array
        4. `.pop()`: remove element from the end of an array
        5. `.unshift()`: add element to the beginning of an array
        6. `.shift()`: remove element from the beginning of an array
        7. `.forEach(func)`
    8. Object: `let myVariable = {name: "spot", breed: "Dalmatian"}; myVariable.name; myVariable["name"]`
        1. use `delete` to remove properties, assigning `null` or `undefined` value will not work
5.  Operators
    1. Arithmetic: `+ - * / % ** << >> >>> & ^ | ++ --`
    2. Assignment: `= += -= *= /= %= **= <<= >>= >>>= &= ^= |=`
    3. Logical: `&& || !`
    4. Equality: `=== !== > < >= <=`

### Branch {-}

1. `if`
2. `switch`
3. `expr?expr1:expr2`

```javascript
if (expr) {
...
} else if (expr) {
...
} else {
...
}

switch (expr) {
    case exp1:
    ...
    break;
    case exp2:
    ...
    break;
    ...
    default:
    ... 
}
```

### Loops {-}

1. `for (let i = 0; i < 10; i++) {...}`
2. `for (... in ...)`
3. `while(expr) {...}`
4. `do {...} while (expr)`
5. `break`: exit a loop
6. `continue`: skip to next iteration of the loop

### Function {-}

JavaScript has a `Function` object which uses `return` to specify the value to return. Wihout `return`, in the case of constructor called with `new`, an object is returned; otherwise an `undefined` value is returned.

```javascript
function add(a, b) {
    let result = a + b
    return result
}
```

### Class {-}

#### Construction Function {-}

JavaScript uses *construction functions* to define and initialize objects and their features. It's JavaScript's version of a class and has following characteristics:

1. name starts with a capital letter
2. return nothing, just define properties and methods
3. use `new` to create a new object instance
4. use `this` to refer to the created object

```javascript
function Person(name) {
    this.name = name;
    this.greeting = function() {
        alert("Hi, I'm " + this.name + ".")
    };

let person1 = new Person("Bob")
let person2 = new Person("Sarah")
}
```

#### Prototypes {-}

Prototypes are the mechanism by which JavaScript objects inherit features from one another. An object's prototype object may also have a prototype object, which it inherits methods and properties from, and so on. This is often referred to as *prototype chain*.

In JavaScript, a link is made between the object instance and its prototype (`__proto__`, which is derived from the `prototype` property on the constructor). Since ECMAScript2015, `Object.getPrototypeOf(obj)` can access object's prototype, similar to `__proto__`.

[Object.create](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/create)

```javascript
function Teacher(first, last, age, subject) { 
    Person.call(this, first, last, age); // call super constructor
    this.subject = subject;
}

Teacher.prototype = Object.create(Person.prototype); // subclass inherits superclass

Teacher.prototype.constructor = Teacher // or the following
Object.defineProperty(Teacher.prototype, 'constructor', { 
    value: Teacher, 
    enumerable: false, // so that it does not appear in 'for in' loop 
    writable: true
    }
);

Teacher.prototype.greeting = function() { ... };
```

1. `this`: refer to the current object
2. `.__proto__`: `.prototype`
3. `.valueOf()`: return the value of the object it is called on
4. `Object.getPrototype(obj)`
5. `delete`: delete an attribute
6. `hasOwnProperty()`: whether the object has its own property, not from prototype, e.g., `({})`.hasOwnProperty.call(foo, "bar")

### Common Functions {-}

#### Number {-}

1. `Math.random()`
2. `Math.floor()`
3. `Math.pow()`

#### String {-}

1. `+`: join strings, `"hello" + "world"`
2. `` `hello, ${name}` ``: template literals, using backtick `` ` ``

#### Browser {-}

1. `prompt()`
2. `alert()`
3. `console.log()`
4. `typeof typeof()`

## DOM

### Selectors {-}

1. `document.querySelector("p")`
2. `document.querySelectorAll("P")`
3. `document.createElement("p")`
4. `document.body.appendChild(para)`
5. `document.body.removeChild(para)`
6. `resetButton.parentNode.removeChild(resetButton)`
7. `ele.children`
8. `ele.setAttribute("class", "message")`

### Styles {-}

Use `ele.style` to specify element styles.

1. `.backgroundColor = "red"`
2. `.fontSize = "200%"`
3. `.padding = "10px"`
4. `.boxShadow = "3px 3px 6px solid"`
5. `.backgroundImage = "url(icons/warning.png)"`

### Elements {-}

1. common
    1. `.nodeName`
    2. `.match()`
2. `<p></p>`
    1. `.textContent = "start it"`
3. `<input />`
    1. .value = "10"
    2. `.focus()`
    3. `.disable = [true, false]`
4. `<button></button>`
    1. `.textContent = "start it"`
5. `<select></select>`
    1. `.value`

### Events {-}

Event types:

1. DOMContentLoaded
2. click
3. change

Event objects:

1. `e.target.nodeName`
2. `e.target.tagName`
3. `e.target.style.backgroundColor = "black"`
4. `e.preventDefault()`
5. `e.stopPropagation()`: stop event bubbling further

Event process

1. `elm.addEventListener("click", function)`: different functions can add to the same event
2. `elm.removeEventListener()`
3. `elm.onclick = function() {}`
4. `elm.ondblclick`
5. `elm.onchange`
6. `elm.onfocus`
7. `elm.onblur`
8. `elm.onmouseover`
9. `elm.onmouseout`
10. `elm.onsubmit`
11. `window.onkeypress`
12. `window.onkeydown`
13. `window.onkeyup`

## NPM

NPM is the Package Manager for Node.js modules.

1. `npm install (i)`
    1. `--global (-g)`
    2. `--save (-S)`: write to dependencies property in `package.json`
    3. `--save-dev (-D)`: write to devDependencies property in `package.json`
    4. `--registry=https://registry.npm.taobao.org`
2.  `npm uninstall`
3. `npm update`
4. `npm list`
5. `npm search`
6. `npm cache clean [--force]`
7. `npm config`
    1. `list`
    2. `set registry http://registry.npm.taobao.org/`

### package.json {-}

1. `npm init`: create `package.json` file
2. `npm help json`: docs about package.json
3. `npm adduser`: register npm user
4. `npm publish`: publish npm package

```json
// package.json
{
    "name": "package name",
    "description": "detail info",
    "version" : "0.0.1",
    "license": "MIT",
    "homepage" : "https://...",
    "author": {"name": "bob", "email" : "mail@mail.com"},
    "contributors": [{"name", "...", "email": "..."}, ...],
    "keywords": ["web", "framework", ...],
    "scripts": {},
    "dependencies": {"accepts": "1.1.1", ...},
    "devDependencies": {...},
    "repository": {"type": "git", "url": "git+https://..."}
}
```

### jsconfig.json {-}

[`jsconfig.json`](https://code.visualstudio.com/docs/languages/jsconfig#_down-level-compilation-with-typescript-compiler) works same as a [tsconfig.json](#ts-tsconfig) file, only with `allowJs` set to true.

## Vue3

[Vue3](https://v3.vuejs.org/guide/introduction.html) is progressive JavaScript Framework for building user interfaces. 


### Installation {-}

1. For quickly start, use latest version via CDN:

    ```js
    <script src="https://unpkg.com/vue@next"></script>
    ```
2. CLI

    ```js
    npm install -g @vue/cli
    vue create <project-name>
    cd <project-name>
    npm run serve
    ```

3. Vite

    ```js
    npm init vite-app <project-name>
    cd <project-name>
    npm install
    npm run dev
    ```

### VS Code Extensions {-}

Install following extensions for [VS Code](#vscode)

1. [Vetur](https://vuejs.github.io/vetur/)
2. [Sass](https://marketplace.visualstudio.com/items?itemName=Syler.sass-indented)
3. [language-stylus](https://marketplace.visualstudio.com/items?itemName=sysoev.language-stylus)
4. [ESLint](https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint)

### Declarative Rendering {-}

At the core of Vue.js is a system that enables us to declaratively render data to the DOM using straightforward template syntax.

1. `{{ counter }}`: text binding, the data will be rendered as plain text compare to `v-html`
   
    ```html
    <div id="counter">
        Counter: {{ counter }}
    </div>
    ```

2. `v-bind`: attribute binding directive
    1. `v-bind:title="message"`
    2. `v-bind:[attrName]="message"`: dynamic attribute binding 
    3. `:title="message"`: shorthand for `v-bind:title="message"`

    
    ```html
    <div id="bind-attribute">
        <span v-bind:title="message">
            Hover your mouse over to see my dynamically bound title!
        </span>
        <span v-bind:[attr]="message">
            Hover your mouse over to see my dynamically bound title!
        </span>
    </div>
    ```
 
3. `v-on`: event binding directive
    1. `v-on:click="reverseMessage"`
    2. `v-on:submit.prevent="onSubmit"`: event modifier using `"."`, bounding in some special way
    3. `v-on:[eventName]="reverseMessage"`: dynamic event binding
    4. `@click="reverseMessage"`: shorthand for  `v-on:click="reverseMessage"`
    5. `@[eventName]="reverseMessage"` shorthand for `v-on:[eventName]="reverseMessage"`
   
    ```html
    <div id="event-handling">
        <p>{{ message }}</p>
        <button v-on:click="reverseMessage">Reverse Message</button>
        <button v-on:[eventName]="reverseMessage">Reverse Message</button>
    </div>
    ```

4. `v-model`: two-way binding directive between form input and app state

    ```html
    <div id="two-way-binding">
        <p>{{ message }}</p>
        <input v-model="message" />
    </div>
    ```

5. `v-if`: conditional directive

    ```html
    <div id="conditional-rendering">
        <span v-if="seen">Now you see me</span>
    </div>
    ```

6. `v-for`: loops directive
   
    ```html
    <div id="list-rendering">
        <ol>
            <li v-for="todo in todos">
                {{ todo.text }}
            </li>
        </ol>
    </div>
    ```

7. `v-once`: one-time interpolations, do not update on data change

    ```html
    <span v-once>This will never change: {{ msg }}</span>
    ```

8. `v-html`: real HTML directive

    ```html
    <p>Using mustaches: {{ rawHtml }}</p>
    <p>Using v-html directive: <span v-html="rawHtml"></span></p>
    ```

    ```js
    const app = {
        data() {
            return {
                message: "Hello, Vue.js!",
                counter: 0,
                seen: true,
                todos: [
                    {text: "Learn Javascript"},
                    {text: "Learn Vue"},
                    {text: "Build something awesome"},
                ]
            }
        },
        mounted() {
            setInterval(() => {
                this.counter++
            }, 1000)
        },
        methods: {
            reverseMessage() {
                this.message = this.message.split("").reverse().join("")
            }
        }
    }

    Vue.createApp(app).mount("#counter")
    ```

### Component

The component system allows building large-scale applications composed of small, self-contained, and often reusable components. Almost any type of application can be abstracted into a tree of components.

```html
<div id="todo-list-app">
    <ol>
        <todo-item
            v-for="item in groceryList"
            v-bind:todo="item"
            v-bind:key="item.id"
        ></todo-item>
    </ol>
</div>
```

```js
const TodoList = {
  data() {
    return {
      groceryList: [
        { id: 0, text: 'Vegetables' },
        { id: 1, text: 'Cheese' },
        { id: 2, text: 'Whatever else humans are supposed to eat' }
      ]
    }
  }
}

const app = Vue.createApp(TodoList)

app.component("todo-item", {
    props: ["todo"],
    template: `<li>{{ todo.text }}</li>`
})

app.mount("#todo-list-app")
```
