# File Format

## Json {#ff-json}

1. Basic
    1. File Extension: `.json`
    2. MIME Type: `application/json`
2. Separators
    1. `:`: `key:value`
    2. `,`: `key:value` pairs
3. Data Types	
    1. keys: string
    2. value
        1. string: "purple", wrapped by double quotes
        2. number: `100`, `-10.2`
        3. boolean: `[true, false]`
        4. null: `{"age": null}`
        5. object: `{..., ...}`
            1. using `.` or  `[]` to get value: `auther.name` or `auther["name"]`
            2. using `=` to update values: auther.name = "othername"
            3. using `delete` to delete properties: `delete auther.name`
        6. array: `[..., ...]`
            1. using `[]` to get value: `auther.books[1]`
            2. using `=` to update values: `auther.books[1] = "hl"`
            3. using `delete` to delete items: `delete auther.books[1]`
4. Schema: describe json structure.

    ```json
    // schema:
    { 
        "$schema": "http://json-schema.org/draft-04/schema#", 
        "title": "Person", 
        "description": "A person", 
        "type": "object",
        "properties": { 
            "name": { 
                "description": "A person's name", 
                "type": "string" 
             },
             "age": {
                "description": "A person's age",
                "type": "number", 
                "minimum": 18,
                "maximum": 64
                } 
        },
        "required": ["name", "age"]
    }
    ```
    ```json
    // object:
    {
        "name": "John Doe",
        "age": 35
    }
    ```

## YAML {#ff-yaml}

1. syntax
    1. files can optionally begin with `---` and end with `...` indicating the start and end of the file
    2. `: `: indicate a mapping
    3. `: {`: indicate a dictionry
    4. ` #`: indicate a comment
    5. when `: ` , `: {`, ` #` appear in the mid of value, use single or double quotes to quote the entire value, not part of it
    6. double quotes can use escapes
2. data types
    1. numeric: `1, 1.1`
    2. boolean: `yes | no | true | false | True | False | TRUE | FALSE`
    3. string: `"hello"`, needs single or double quotes when needed
    4. list: members begin at the same indentation level starting with a dash and a space `- `
    5. dictionray
        1. `key: value`: colon must be followed by a space
        2. value can span multiple lines using `|` or `>`
            * `|` will include the new lines and any trailing spaces
            * `>` will fold new lines to spaces making long line to read and edit easier
            * both `|` and `>` will ignore the indentation

    ```yaml
    # Employee records
    - martin: 
        name: Martin D'vloper
        job: Developer
        skills:
          - python
          - perl
          - pascal
    - tabitha:
        name: Tabitha Bitumen
        job: Developer
        skills:
          - lisp
          - fortran
          - erlang
    
    --- 
    # An employee record
    name: Martin D'vloper
    job: Developer
    skill: Elite
    employed: True
    foods:
      - Apple
      - Orange
      - Strawberry
      - Mango
    languages:
      perl: Elite
      python: Elite
      pascal: Lame
    education: |
      4 GCSEs
      3 A-Levels
      BSc in the Internet of Things
    ...
    ```
