# OS

## Environments

1. Centos
    1. download [minimal centos image](http://centos.nethub.com.hk/7.9.2009/isos/x86_64/CentOS-7-x86_64-Minimal-2009.    iso) 
    2. install and partition disk
        1. select **install centos7** after booting
        2. click **tab** at the bottom of the information, append **inst.gpt**, then press **enter** key, the system will use **gpt** to partition the disk
    3. file system
        1. **2M** for **biosboot**, using **standard partition**
        2. **1G** for **/boot**, using **standard partition** and **xfs** filesystem
        3. **/**, **/home**, **swap** using **lvm** and **xfs** filesystem, specify storage size
    4. QA
        1. `Cannot find a valid baseurl for repo`: in `/etc/sysconfig/network-scripts/ifcfg-ens33`, changes `ONBOOT=no` to `ONBOOT=yes`, then `systemctl restart network`
        2. `time not correct`

            ```
            yum install ntp
            ntpdate us.pool.ntp.org # correct time
            ```
2. Basic Software
    1. Minimal: `yum install gcc wget net-tools nss curl libcurl curl-devel epel-release`
        1. `gcc`, `wget`, `net-tools`: for minimal centos7
        2. `nss`, `curl`, `libcurl`, `curl-devel`: net protocals and avoid `peer reports incompatible or unsupported         protocol version`
        3. `epel-release`: download software from epel-release repository, it contains new version software
    2. Git
        1. dependencies: `yum install autoconf zlib-devel perl-ExtUtils-MakeMaker asciidoc xmlto`
            1. `autoconf`: for generating configure file
            2. `asciidoc`, `xmlto`: for generating docs
        2. source
            1. tar

                ```sh
                # GIT_VERSION=2.9.5
                GIT_VERSION=2.35.0
                wget https://mirrors.edge.kernel.org/pub/software/scm/git/git-${GIT_VERSION}.tar.xz`
                ```
            2. git: `git clone https://github.com/git/git.git`
        3. install

            ```sh
            make configure && ./configure --prefix=/usr/local && make all doc
            sudo make install install-doc install-html
            ```
    3. Tmux
        1. dependencies: `sudo yum install automake libevent libevent-devel ncurses-devel`
            1. `automake`, `libevent`, `libevent-devel`: for generating `autogen.sh`
        2. source from tar 

            ```sh
            wget https://github.com/tmux/tmux/releases/download/3.2a/tmux-3.2a.tar.gz
            ./configure && make && sudo make install
            ```
        3. source from git

            ```sh
            git clone https://github.com/tmux/tmux.git
            cd tmux && sh autogen.sh && ./configure 
            make && sudo make install
            ```
        4. config: `~/.tmux.conf`, see `files\deploy\rc\.tmux.conf`

            ```sh
            # from deploy/rc/.tmux.c
            # reset prifix key, mapping to C-a, when tmux does not use zsh, may need reboot
            unbind C-b
            set -g prefix C-a
            # r: reload config file
            bind r source-file ~/.tmux.c
            # remap panel navigation like vim
            unbind-key j
            bind-key j select-pane -D
            unbind-key k
            bind-key k select-pane -U
            unbind-key h
            bind-key h select-pane -L
            unbind-key l
            bind-key l select-pane
            setw -g mode-keys vi
            ```
        5.Operations
            1. `t`: display time in the current panel
            2. `[`: enter copy mode, press space-key to select content, then press enter-key to end copy
            3. `]`: paste the content
            4. `q`: exit 
            5. panel operation
                1. `%`: add a vertical panel
                2. `"`: add a horizontal panel
                3. `x`: close current panel
                4. `q`: list panel number
                5. `o`: move between panels
                6. `{`: move the current pane left
                7. `}`: move the current pane right
                8. ` `: toggle between layouts
                9.  `!`: display panel in new window
                10. arrow key: move between panels
                11. Esc or `Alt + arrow`: resize panel size
            6. widow operation
                1. `c`: create a window
                2. `&`: kill window
                3. `,`: rename current window
                4. `w`: list all windows
                5. `n`: select next window
                6. `p`: select previous window
                7. `number(1, 2, 3)`: move between windows
            7. session operation
                1. `tmux new -s session-name`: add a session
                2. `: new -s session-name`: add a session in an existing session
                3. `tmux kill-session -t session-name`: close a session
                4. `$`: rename current session
                5. `: rename-session new-session-name`
                6. `tmux ls`: list session
                7. `s`: list session
                8. `tmux attach`: enter existing sessions
                9. `tmux a -t session-name`: attach a specified session
                10. `tmux detach`: detach a session
                11. `d`: also detach a session
    4. Python
        1. dependencies: `yum install readline-devel openssl-devel sqlite-devel bzip2-devel libffi-devel`
            1. `readline-devel`:  for cursor moving, like backspace and direction key
            2. `openssl-devel`: for https protocal
            3. `sqlite-devel`: for ipython to record history
            4. `bzip2-devel`: for matplotlib use
            5. `libffi-devel`: for python since 3.7.0
        2. source from tar

            ```sh
            # PYTHON_VERSION = 3.7.0
            PYTHON_VERSION = 3.10.4
            wget https://www.python.org/ftp/python/${PYTHON_VERSION}/Python-${PYTHON_VERSION}.tgz
            tar xf Python-${PYTHON_VERSION}.tgz
            ```
        3. install

            ```sh
            # --enable-shared: generate shared dynamic python library, then other applications can depend it
            # --prefix=/usr/local
            ./configure --enable-shared && make
            sudo make install
            # sudo make altinstall (instead of make install) support multiple python versions
            ```
        4. QA
            1. `export LD_LIBRARY_PATH=/usr/local/lib:${LD_LIBRARY_PATH}`
    5. Vim
        1. dependencies
            1. Python
            2. `export LD_LIBRARY_PATH=/usr/local/lib:${LD_LIBRARY_PATH}`: find libpython3.7m.so.1.0
        2. source from git: `git clone https://github.com/vim/vim.git`
        3. install

            ```sh
            ./configure --enable-fail-if-missing --enable-multibyte --enable-python3interp=yes \
              --with-python3-config-dir=/usr/local/lib/python3.7/config-3.7m-x86_64-linux-gnu
             make && sudo make install
            # rm vim/src/auto/config.cache: if report cache error
            ```
        4. config
            1. `~/.vimrc`, see `files\deploy\rc\.vimrc`
            2. package management plugin `vundle`

                ```sh
                git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim
                vim +PluginInstall +qall
                ```
    6. Zsh
        1. source from git: `git clone git://git.code.sf.net/p/zsh/code zsh`
        2. install

            ```sh
            ./Util/preconfig # genterates configuration file
            ./configure && make && sudo make install
            ```
        3. Configurations
            1. modify default shell: ``sudo usermod -s `which zsh` ${USER}``
            2. omz: ``sh -c "`curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh`"``
            3. autojump: `sudo yum install autojump-zsh`
            4. `.zshrc`: see `files\deploy\rc\.shrc`, `cat files\deploy\rc\.shrc >> ~/.zshrc`
    7. Cmake
        1. dependencies: `yum install gcc-c++`
        2. source from tar

            ```sh
            CMAKE_VERSION=3.13.0
            wget https://github.com/Kitware/CMake/releases/download/v${CMAKE_VERSION}/cmake-${CMAKE_VERSION}.tar.gz
            tar xf cmake-${CMAKE_VERSION}.tar.gz
            ```
        3. install: `./bootstrap && make && sudo make install`

    8. SVN: `yum install svn`
    9. Clang
        1. dependencies
            1. Cmake
            2. SVN
        2. source from SVN
            1. structure
                1. llvm/
                2. llvm/tools/clang/
                3. llvm/projects/compiler-rt/
                4. llvm/tools/clang/tools/extra/
            2. download

                ```sh
                svn co http://llvm.org/svn/llvm-project/llvm/trunk llvm
                cd llvm/tools && svn co http://llvm.org/svn/llvm-project/cfe/trunk clang
                cd ../projects && svn co http://llvm.org/svn/llvm-project/compiler-rt/trunk compiler-rt
                cd ../tools/clang/tools && svn co http://llvm.org/svn/llvm-project/clang-tools-extra/trunk extra
                ```
        3. install

            ```sh
            LLVM_BUILD_HOME=/llvm/build/home # blank directory for compiled llvm
            cd ${LLVM_BUILD_HOME}
            cmake -G 'Unix Makefiles' -DCMAKE_BUILD_TYPE=Release src/llvm  # src/llvm is llvm source from svn
            make -j4 // build with 4 cores
            sudo make install
            ```
    10. YCM
        1. dependencies
            1. Python
            2. Clang
        2. Source from git
            1. download YouCompleteMe from vundle
            2. download submodule: `cd ~/.vim/bundle/YouCompleteMe && git submodule update --init --recursive`
        3. install
            1. `--system-libclang`: use local clang, otherwise download upstream clang binary
            2. `--clang-completer`: support c-family languages
            3. `--ts-completer`: support javascript and typescript

            ```sh
            cd ~/.vim/bundle/YouCompleteMe
            python3 install.py --system-libclang --clang-completer --ts-completer
            ```
    11. NVM

        ```sh
        NVM_VERSION=0.33.11
        git clone https://github.com/creationix/nvm.git ~/.nvm
        cd ~/.nvm && git checkout v${NVM_VERSION}
        ```
    12. Node
        1. dependencies
            1. nvm
        2. install: `nvm install node`
    13. Pandoc
        1. dependencies
            1. stack: `curl -sSL https://get.haskellstack.org/ | sh`
        2. source from git

            ```sh
            PANDOC_VERSION=2.5
            git clone https://github.com/jgm/pandoc
            cd pandoc && git checkout ${PANDOC_VERSION} && git submodule update --init
            ```
        3. install: `stack setup && stack install --flag pandoc:embed_data_files`
    14. Textlive
        1. dependencies: `yum install perl-Digest-MD5`
        2. source from tar

            ```sh
            wget http://mirror.ctan.org/systems/texlive/tlnet/install-tl-unx.tar.gz
            tar xf install-tl-unx.tar.gz
            ```
        3. install: `sudo ./install-tl # may take long time`
    15. Nginx
        1. install
            1. from repo
                1. `nginx.repo`: `files\deploy\repo\nginx.repo`
                2. install
                
                    ```sh
                    cp nginx.repo /etc/yum.repos.d/
                    install
                    sudo yum install nginx
                    ```
            2. source from tar
                1. dependencies
                    1. prce

                        ```sh
                        PCRE_VERSION = 8.42
                        wget ftp://ftp.csx.cam.ac.uk/pub/software/programming/pcre/pcre-${PCRE_VERSION}.tar.gz
                        tar xf pcre-${PCRE_VERSION}.tar.gz && mv pcre-${PCRE_VERSION} pcre && cd pcre
                        ./configure && make # && sudo make install
                        ```
                    2. zlib

                        ```sh
                        ZLIB_VERSION = 1.2.11
                        wget http://zlib.net/zlib-${ZLIB_VERSION}.tar.gz
                        tar xf zlib-${ZLIB_VERSION}.tar.gz && mv zlib-${ZLIB_VERSION} zlib && cd zlib
                        ./configure && make # && sudo make install
                        ```         
                    3. openssl

                        ```sh
                        OPENSSL_VERSION = 1.1.1
                        wget http://www.openssl.org/source/openssl-${OPENSSL_VERSION}.tar.gz
                        tar xf openssl-${OPENSSL_VERSION}.tar.gz && mv openssl-${OPENSSL_VERSION} openssl && cd openssl
                        ./config && make # && sudo make install
                        ```
                2. source

                    ```sh
                    NGINX_VERSION = 1.15.5
                    wget http://nginx.org/download/nginx-${NGINX_VERSION}.tar.gz
                    ```
                3. Install
                    1. `/usr/local/nginx`: default installed directory
                    2. `--with-stream` or `--with-stream=dynamic`: enable tcp proxy compiled dynamically
                    3. `--with-mail` or `--with-mail=dynamic`: enables mail proxy which can also be compiled dynamically

                    ```sh
                    ./configure --with-http_ssl_module --with-openssl=../openssl --with-pcre=../pcre --with-zlib=../zlib --with-stream --with-mail=dynamic
                    make && sudo make install
                    ```
                4. Config
                    1. add user nginx

                        ```sh
                        sudo adduser nginx -M
                        sudo passwd nginx
                        sudo chown -R nginx: /usr/local/nginx
                        sudo usermod -d /usr/local/nginx nginx
                        ```
                    2. `nginx.service`: `files\deploy\service\nginx.service`
                    3. `nginx.conf`

                        ```
                        user nginx
                        worker_process 4 # limit to the cores
                        ```
                    4. firewall

                        ```sh
                        sudo firewall-cmd --permanent --add-port=80/tcp
                        sudo systemctl reload firewalld
                        ```
                    5. services: `sudo cp nginx.service /usr/lib/systemd/system`
                        1. start: `systemctl start nginx`
    16. Docker
        1. install from repo

            ```sh
            sudo yum install yum-utils device-mapper-persistent-data lvm2
            sudo yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
            sudo yum install docker-ce
            ```
        2. Config
            1. `daemon.json`

                ```json
                {
                    "bip": "192.168.188.1/24"
                }
                ```

                ```sh
                mkdir -p /etc/docker
                cp daemon.json /etc/docker/
                chmod 600 /etc/docker/daemon.json
                ```
            2.  override.conf

                ```ini
                #override.conf: deploy/files/conf/docker/override.conf
                [Service]
                ExecStart=
                ExecStart=/usr/bin/dockerd -H unix:// -H tcp://127.0.0.1:2375
                ```
                ```sh
                sudo cp override.conf /etc/systemd/system/docker.service.d # or systemctl edit docker.service
                sudo systemctl daemon-reload
                sudo systemctl restart docker
                ```
        3. services
            1. start: `sudo systemctl start docker`

## Bash

1. References
    1. [docopt](http://docopt.org/)
    2. [Command-line syntax](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/command-line-syntax-key)
2. Command Line Style
    1. Elements
        1. program and (sub)command name
        2. positional arguments
        3. options
            1. short: start with `-`
                1. `-l`
                2. `-o output.csv`: option with argument
                3. `-abc`: stack way, equivalent to `-a -b -c`
                4. `-fFILE`: equivalent to `-f FILE`, may ambiguous to stacked short options
            2. long: start with `--`
                1. `--list`
                2. `--output=output.csv`: option with argument using `=`
                3. `--output output.csv`: option with argument using space, may ambiguous whether the value is option's argument or a position argument
    2. Format
        1. `command_name`: text without brackets or braces that must type
        2. `<text inside angle brackets>`: placeholder for positional argument
        3. `(item1 item2)`: required items
        4. `[item1 item2]`: optional items
        5. `|`: mutual-exclusive elements
            1. `(|)`: must choose one
            2. `[|]`: optionally choose one
        6. `element...`: repeating items
        7. `[options]`: shortcut that allow to avoid listing all options
        8. `--`: double dash, often used to separate options and positional arguments
        9.  `-`: s single dash, often used to signify the program can process `stdin` as opposed to a file
        10. `[default: <value>]`: specify default value in the description, e.g., `[default: 10]`
    3. Usage
        1. `my_program (move | cp | delete) [-p | -r] <file>...`
        2. `my_program [options] <path>`
        3. `my_program [options] [--] <file>...`
3. Commands
    1. System
        1. reboot: `reboot`
        2. os: `uname -s => [Linux, Darwin, MINGW*|MSYS_NT*]`
        3. environment variable
            1. `PATH`
            2. `SHLVL`: shell level
        4. logging users: `users`
        5. cpu
            1. Linux: `cat /proc/cpuinfo`
                1. `physical id`: physical cpus
                2. `cpu id`: cores in each phisical cpu
                3. `processor`: threads in each core
                4. total threads = `1 * 2 * 3`
            2. Windows: `wmic` enter interactive shell, then execute `cpu get`
                1. NumberOfCores
                2. NumberOfLogicalProcessors
        6. memory: `free -h`
        7. disk: `df -lh`
    2. Basic
        1. `basename`
        2. `dirname`
        3. `set`: displays environment variables and shell functions
            1. `set -e`: exit whenever produces a false result 
            2. `set +e`: continues executing when meets false
        4. `exit 1`: exit with return value 1 immediately
    3. User
        1. `/etc/passwd`: users file
        2. `adduser -M <user_name>`
            1. `-M, --no-create-home`: create user without login directory
            2. `-d, --home-dir`: login directory
            3. `-s, --shell`: user's login shell
        3. `userdel <user_name>`
        4. `usermod`:
            1. `usermod -d <user_home> <user_name>`: set login directory
            2. `usermod -s $(which zsh) <user_name>`: set default shell
            3. `usermod -a -G <groupname> <user_name>`
        5. `passwd <user_name>`: set password
        6. `chown -R <user_name>: <user_home>`
        7. `groupadd <groupname>`
        8. `gpasswd -a <user_name> wheel`: `wheel`, add sudo priviledge
    4. SSH
        1. operations
            1. `ssh-keygen -t rsa`: create keys, stored in `~/.ssh` default
                1. `id_rsa.pub`: public key file, put this key to remote's `authorized_keys` file for logging without password
                2. `id_rsa`: private key file, must keep safely
                3. `authorized_keys`: file storing login user's public key, must have **mode 600**, otherwise will not work
                4. `known_hosts`: trust hosts
            2. `ssh-copy-id user@host`: copy public key to remote host
            3. `ssh user@host 'mkdir -p .ssh && cat >> .ssh/authorized_keys' < ~/.ssh/id_rsa.pub`: same as `2`
        2. Config: see `man ssh_config`
            1. files
                1. `/etc/ssh/ssh_config`: system-wide file
                2. `~/.ssh/config`: user's file

                ```
                Host server1
                    HostName 192.168.1.0
                    User hello
                    Port 2322
                    IdentityFile ~/.ssh/id_rsa

                Host server2
                    HostName 192.168.2.0
                    User world
                ```
            2. login: `ssh server1`
        3. QA
            1. `/usr/bin/ssh-copy-id: ERROR: No identities found`: make sure public key has been generated, using `ssh-keygen`
    5. Systemd
        1. `systemctl set-default (multi-user.target | graphical.target)`: text or graphical mode
        2. `systemctl [start multi-user.target, graphical.target]`
        3. `/usr/lib/systemd/system/`: system path
        4. `/etc/systemd/system/`: customize path, overrides system config
        5. `systemctl edit <service_name.service>`: changes service configurations
        6. `systemctl [start|stop|status|restart|reload|enable|disenable] <service_name.service>`
    
        ```ini
    
        # service file example
        #/usr/lib/systemd/system/postgresql.service
        ...
        [Service]
        ...
        Environment=PGPORT=5432
        ...
        
        # /etc/systemd/system/postgresql.service
        .include /usr/lib/systemd/system/postgresql.service
        [Service]
        Environment=PGPORT=5433
        ...
        ```
    6.  Firewall
        1. `firewall-cmd --permanent --add-service=<postgresql>`
        2. `firewall-cmd --permanent --add-port=<6379/tcp>`
        3. `systemctl reload firewalld`
4. Conditional Structure
    1. `if`

        ```sh
        if expr; then
            ...
        elif expr; then
            ...
        else
            ...
        fi
        ```

    2. `case`
    
        ```sh
        case $(uname -s) in
            Darwin|Linux)
                ...
                ;;
            MINGW*|MSYS_NT*)
                ...
                ;;
    
            *)
                ...
                ;;
        ecac
    ```
