# MySQL

1. Deployment
    1. MySQL
        1. [install guide](https://dev.mysql.com/doc/mysql-yum-repo-quick-guide/en/)
        1. [download repo](https://dev.mysql.com/downloads/repo/yum/)
        2. check md5: `md5sum mysql80-community-release-el7-6.noarch.rpm`
        3. install repo in `/etc/yum.repos.d`: `sudo rpm -ivh mysql80-community-release-el7-6.noarch.rpm`
        4. install mysql: `sudo yum install mysql-community-server`
            1. `--nogpgcheck`, when `GPG key retrieval failed: [Errno 14] curl#37 - "Couldn't open file /etc/pki/rpm-gpg/RPM-GPG-KEY-mysql-2022"`
        5. start mysql: `sudo systemctl start mysqld`
        6. get temprory passwd: `sudo grep 'temporary password' /var/log/mysqld.log`
        7. config: `mysql_secure_installation`
        8. outer access for MySQL8: `CREATE USER 'root'@'%' IDENTIFIED BY 'root'; GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' WITH GRANT OPTION;`
        9. Q&A
            1. `MySQL 8.0 Public Key Retrieval is not allowed`
                1. dbeaver: `Driver properties -> allowPublicKeyRetrieval: TRUE`
                2. connection: `allowPublicKeyRetrieval=true`
    2. Mariadb
        1. Dependencies
            1. MariaDB.repo

                ```
                # MariaDB 10.3 CentOS repository list
                # http://downloads.mariadb.org/mariadb/repositories/
                # 10.3
                
                [mariadb] name = MariaDB
                baseurl = http://yum.mariadb.org/10.6/centos7-amd64 
                gpgkey=https://yum.mariadb.org/RPM-GPG-KEY-MariaDB
                gpgcheck=1
                ```
        2. Install

            ```sh
            cp MariaDB.repo /etc/yum.repos.d/
            sudo yum install MariaDB-server MariaDB-client
            mysql_secure_installation
            ```
        3. Configurations
            1. change datadir and port
                1. make new datadir and give permission to the account

                    ```sh
                    MARIADB_DATA_HOME=/mariadb/home
                    mysql -u root -p -e "select @@datadir, @@port"
                    sudo chown -R mysql: ${MARIADB_DATA_HOME}
                    sudo cp -R -p /var/lib/mysql/* ${MARIADB_DATA_HOME}
                    ```
                2. may need selinux settings for centos

                    ```sh
                    sudo semanage fcontext -a -t mysqld_db_t "${MARIADB_DATA_HOME}(/.*)?"
                    sudo restorecon -R ${MARIADB_DATA_HOME}
                    ```
                3. set new port in the file `/etc/my.cnf.d/server.cnf`, may need the following settings

                    ```sh
                    MARIADB_PORT=3308 # 3306 default
                    sudo yum install policycoreutils-python
                    sudo semanage port -a -t mysqld_port_t -p tcp ${MARIADB_PORT}
                    ```
            2. `/etc/my.cnf`

                ```ini
                # /etc/my.cnf
                [client-server]

                [mysqld]
                datadir=${MARIADB_DATA_HOME} # use actual value, not variable
                socket=${MARIADB_DATA_HOME}/mysql.sock

                [client]
                socket=${MARIADB_DATA_HOME}/mysql.sock

                !includedir /etc/my.cnf.d
                ```
            3. `/etc/my.cnf.d/server.cnf`

                ```ini
                # /etc/my.cnf.d/server.cnf
                [mysqld]
                port=3308
                ```
            4. `~/.my.cnf`: set login info, and connect to the db using `mysql --defaults-group-suffix=host1`

                ```ini
                # ~/.my.conf
                [clienthost1] # or [client]
                host=localhost
                port=port
                socket=/tmp/mysql.sock
                database=dbname
                user=username
                password=passwd

                [clienthost2]
                ...
                ```
        4. Services
            1. start: `systemctl start mariadb.service`
2. reset root password
    1. `/etc/mysqld`, add `skip-grant-tables` under `[mysqld]` part
    2. restart mysql server
    3. `mysql -uroot -p` login the server
    4. `update mysql.user set authentication_string=password('*****') where user='root'`
    5. remove `skip-grant-tables` content
    6. restart the server
3. create user
    1. `create user 'user1'@'%' identified by 'ThePassword';`
    2. `grant all on db_example.* to 'user1'@'%';`
4. open binlog
    1. `/etc/my.cnf`: for 5.7
        1. `[mysqld]`
            1. `server-id=<1>`: 5.7+
            2. `log_bin=mysql-bin`
            3. `binlog_format=row`
            4. `binlog_row_image={<default: FULL>, minimal, noblob}`: use default, only set according to demand, `show variables like 'binlog_row_image'`
            5. `expire_logs_days=10`
            6. `binlog_rows_query_log_events=ON`: make binlog containning original SQL statements
    2. restart MySQL
    3. check: `SELECT variable_value FROM information_schema.global_variables WHERE variable_name='log_bin'`
    4. user access
        1. `CREATE USER 'user'@'localhost' IDENTIFIED BY 'password';`
        2. `GRANT SELECT, RELOAD, SHOW DATABASES, REPLICATION SLAVE, REPLICATION CLIENT ON *.* TO 'user';`
        3. `FLUSH PRIVILEGES;`
5. Command
    1. Database
        1. create: `create database flow default character set utf8mb4 default collate utf8mb4_unicode_ci`
    2. User
        1. create: `create user flow identified by 'flow';`
    3. Grant: `grant <privilege>... on <dbname>.<table> to 'user'@'host'`, need flush `flush privileges`
        1. list: `show grants for 'flow'`
        2. add: `grant all privileges on flow.* to 'flow'@'%'`
    4. Revoke: `revoke <privilege>... on <dbname>.<table> from <user>`
      1. Privileges
        1. `all`
        2. Table Level
            1. `create`
            2. `index`
            3. `alter`
            4. `drop`
            5. `select`
            6. `insert`
            7. `update`
            8. `delete`
        3.  Administrative Level: for the whole database, should use `on *.*`
            1. `create user`
            2. `super`
            3. `shutdown`
            4. `show databases`
            5. `process`
            6. `reload`
                1. `flush privileges`
                2. `flush tables`
                3. `flush logs`
            7. `replication slave`
            8. `replication client`

