# Idea

1. Settings
    1. Editor
        1. File Encoding: `Editor/File Encoding: UTF-8`
        2. Line Separator: `Editor/Code Style/Line separator: \n`
        3. Templates: `Editor/File and Code Templates`
    2. Imports: `Code Style.java.Imports`
        1. `Class count to use import with '*': 500`
        2. `Names count to use static import with '*': 500`
    3. Maven mirrors
        1. `Build Tools -> Maven -> User settings file`
    4. Run
        1. add command line arguments: `Run -> Edit Configurations -> select Application -> Program Arguments`
2. Shortcuts
    1. `Ctrl + N`: next item
    2. `Ctrl + P`: previous item
    3. `Ctrl + Click`: jump to definition
    4. `Ctrl + Shift + N`: open file
    5. `Ctrl + Alt + L`: format code
    6. `Ctrl + /`: line comment
    7. `Ctrl + Shift + /`: block comment
    8. `Alt + Ins`: insert dependencie
    9. `Ctrl + H`: show type hierarchy
3. Plugins
    1. IdeaVim
        1. `~/.ideavimrc`
4. Project
    1. Notes
        1. `Command line is too long`

            ```xml
            <!-- .idea/workspace.xml add item "dynamic.classpath" -->
            <component name="PropertiesComponent">
            <property name="dynamic.classpath" value="true" />`
            </component>
            ```
        2. `encoding shown error`
            1. `Settings -> File Encoding`
                1. `Global Encoding: UTF-8`
                2. `Project Encoding: UTF-8`
                3. `Default encoding for properties Files: UTF-8`
            2. `idea/bin/idea64.exe.vmoptins`: add `-Dfile.encoding=UTF-8`
            3. `idea -> help -> Edit Custom VM Options`: add `-Dfile.encoding=UTF-8`
            4. `Configuration -> VM options: -Dfile.encoding=UTF-8`
        3. `Lombok Requires Annotation Processing`: `Settings → Build -> Compile: Annotation Processors, add "Enable annotation processing"`
    2. Run output not work in Vim mode: select some output, then works
    3. Scala
        1. download scala plugin
        2. may need `Add Framework Support for scala` when not see `Scala Class` creating scala class file, just right clproject oolder
        3. build sbt
            1. JRE: sbt install home path
            2. VM parameters: `-Duser.language=en`
