# (PART) English Learning {-}

# Daily Conversation

## Acne Treatment 

A: Why do you have a **Band-Aid** (创口贴, 绷带, OK绷) on your face?

B: It's not a Band-Aid, it's an **acne patch** (痘痘贴). I have a big **pimple** (青春痘) here, and I'm hoping the patch will make it go away faster.

A: Oh. I haven't had acne problems since high school. In high school, I had really bad acne.

B: What did you do about it?

A: I bought **over-the-counter** (非处方药) medicine at the pharmacy. When that didn't work, I saw a dermatologist (皮肤科医生) regularly and took prescription drugs (处方药).

B: Did it help?

A: It helped some, but my acne only completely cleared after high school. Then I had to get laser treatment to get rid of the acne scars (伤疤).

B: Thanks for sharing. I won't complain about a single pimple then!

## Meeting Invite

A: Hi Liv, this is Eva. Could you check Grace's calendar and see if she's available for a one-hour meeting next Tuesday at 11 **a.m.** (anti meridiem)?

B: Let me check. Grace will be **out of the office** (不在办公室) on Tuesday. How about Wednesday at 9 a.m.?

A: I'll be on a **business trip** (商务旅行) from Wednesday to Friday next week. Let me see ... How about next Monday at 4 **p.m.** (post meridiem)?

B: Grace is available on Monday at 4 p.m.

A: OK. Let's do Monday at 4 p.m. then. I'll send a meeting invite to you and Grace via Outlook Calendar soon.

B: OK. Bye.

## YouTube

A: What do you like to do in your free time?

B: I love watching YouTube videos.

A: Me, too. What do you watch?

B: **Comedies** (喜剧), mostly. My favorite YouTuber is Ryan Higa.

A: HaHa! He's funny.

B: What do you like to watch?

A: I like to watch **beauty tutorials** (美妆教学) so I can improve my **make-up** (化妆) skills. I also like to watch gaming channels of top gamers.

B: Nice. If you find some interesting new channels. Let me know.

A: OK!

## Gym Membership

A: I'd like to **sign up** (报名) for a **gym membership** (健身房会员). What kinds of plans do you have?

B: We have one-, two- and three-year plans. Would you prefer going to a single location or multiple locations?

A: I'm only living in **LA** (Los Angeles) for one year, so a one-year plan is fine. This location is near my apartment, so single location is good for me.

B: OK.

A: What is the monthly fee? And is there an **initiation fee** (入会费)?

B: The initiation fee is `$99`. The monthly fee for one location is `$29`.

A: That sounds fine. I'll sign up for one year.

B: Great! Please fill out these forms.
