# Daily Expression

Don't wait until everything is just right. It will never be perfect. There will always be challenges, obstacles and less than perfect conditions. So what. Get started now. With each step you take, you will grow stronger and stronger, more and more skilled, more and more self-confident, and more and more successful.

不要等到万事俱备，没有那么完美的事儿。总是会有挑战，障碍，和不够完美的条件。那又怎样。现在就开始行动。每走一步，你会越来越强，越来越熟练，越来越自信，越来越成功。

When it rains, most birds seek shelter. The eagle is the only bird that will fly above the clouds to avoid the rain. Be like the eagle, and push through your storm.

下雨的时候，大多数鸟会寻求庇护。鹰是唯一一种会飞到云层之上去躲雨的鸟。要像鹰一样冲破风暴。

Never compare your results to someone else's. You can never be another person. You can only be a better version of yourself.

永远不要拿自己的成果和别人的比较。你永远也成为不了另一个人。你只能成为更好的自己。

Try to improve by 1% every day. Within a year, you will have improved by 365% (three hundred and sixty five percent). Take one step at a time. Eventually, you will reach your goal.

尝试每天进步1%。 一年之内，你就会进步365%。一步一个脚印。最终，你会达到你的目标的。

Your circle should want to see you win. Your circle should be pushing you forward every day. Your circle should encourage your growth.

你的圈子应该想要看到你的成功。你的圈子应该每天推动你前行。你的圈子应该鼓励你的成长。
