- name: create maven related directory
  file:
    path: "{{ item.value }}"
    state: directory
  loop: "{{ maven_base|dict2items }}"

- name: rsync maven file to remote server
  synchronize:
    src: "apache-maven-{{ maven_version }}"
    dest: "{{ maven_base.bin }}"

- name: configure maven environment
  blockinfile:
    path: "{{ hp_bashrc }}"
    marker: "# {mark} maven variables"
    block: |
      export M2_HOME={{ maven_base.bin }}/apache-maven-{{ maven_version }}
      export PATH=${M2_HOME}/bin:${PATH}
      export MAVEN_OPTS="-Xmx2g -XX:ReservedCodeCacheSize=1024m" # for java8+
