- name: create scala related directory
  file:
    path: "{{ item.value }}"
    state: directory
  loop: "{{ scala_base|dict2items }}"

- name: rsync scala file to remote server
  synchronize:
    src: "scala-{{ scala_version }}"
    dest: "{{ scala_base.bin }}"

- name: configure scala environment
  blockinfile:
    path: "{{ hp_bashrc }}"
    marker: "# {mark} scala variables"
    block: |
      export SCALA_HOME={{ scala_base.bin }}/scala-{{ scala_version }}
      export PATH=${SCALA_HOME}/bin:${PATH}
