### emmet

prefix key is:

    let g:user_emmet_leader_key=',e'

#### symbols

* `$` - auto increment, `$@2` starts from 2, `$@-` descendents
* `*` - multiply
* `^` - father
* `+` - sibling
* `>` - child
* `()` - group
* `#` - id
* `.` - class
* `[]` - self defined attribute
* `{}` - text

#### shortcuts

##### adding

1. `html:5` or `!`

    <!DOCTYPE html>
    <html lang="zh-Hans">
    <head>
        <meta charset="UTF-8">
        <title></title>
    </head>
    <body>
    </body>
    </html>

2. `script:src`

    <script src=""></script>

3. `h$[title=item$]{header $}*3`

    <h1 title="item1">header 1</h1>
    <h2 title="item2">header 2</h2>
    <h3 title="item3">header 3</h3>

4. `ul>li.item$$$*5`

    <ul>
        <li class="item001"></li>
        <li class="item002"></li>
        <li class="item003"></li>
        <li class="item004"></li>
        <li class="item005"></li>
    </ul>

5. `a` `a:link` `a:mail`

    <a href=""></a>
    <a href="http://"></a>
    <a href="mailto:"></a>

##### wrapping

if you have lines:

    test1
    test2
    test3

then do line-wise visual selection, and type `,e,`, you will get to the `tag:`, type `ul>li*`, then get:

    <ul>
        <li>test1</li>
        <li>test2</li>
        <li>test3</li>
    </ul>

if you type a tag, such as `blockquote`, then you'll see:

    <blockquote>
        test1
        test2
        test3
    </blockquote>

##### merging

select the lines, which include `<li>`, 

    <ul>
        <li>test1</li>
        <li>test2</li>
        <li>test3</li>
    </ul>

and then type `,em`, you will get:

    <ul>
        <li>test1</li><li>test2</li><li>test3</li>
    </ul>

##### removing

move cursor in a block, then type `,ek` in **insert mode**, you will remove the block:

    <ul>
        <li></li>
        <li></li>
        <li></li>
    </ul>

    <ul>
        
        <li></li>
        <li></li>
    </ul>

#####  make an anchor from a url

from your url, type `,ea`, you will get an link:

    http://www.google.com

    <a href="http://www.google.com">Google</a>
