## write an R package

An R packages contains:

* an `R/` directory
* a basic `DESCRIPTION` file
* a basic `NAMESPACE` file

### DESCRIPTION

a `DESCRIPTION` file contains:

* `Imports:` - packages listed here must be present for your package to work. if not, they will be installed automatically. use `usethis::use_package("dplyr")` to add the needing `Imports` package
* `Depends:` - `Imports` just loads the package, `Depends` attaches it. There are no other differences
* `Suggests:` - your package can use these packages, but doesn’t require them. they will not be installed automatically. use `requireNamespace(x, quietly = TRUE)` to check if it is available and  use `usethis::use_package("dplyr", "Suggests")` to add the needing `Suggests` package
* `Title:` - is a one line description of the package, and is often shown in package listing. It should be plain text (no markup), capitalised like a title, and NOT end in a period. Keep it short: listings will often truncate the title to 65 characters
* `Description:` - is more detailed than the title. You can use multiple sentences but you are limited to one paragraph. If your description spans multiple lines (and it should!), each line must be no more than 80 characters wide. Indent subsequent lines with 4 spaces
* `Authors@R:` - to identify the package’s author, and whom to contact
* `URL:` -  list other resources available for help
* `BugReports:` - where bug reports should be submitted
* `License:` - can be either a standard abbreviation for an open source license, like `GPL-2` or `BSD`, or a pointer to a file containing more information, `file LICENSE`
* `Version:` - an R package version is a sequence of at least two integers separated by either `.` or `-`

### NAMESPACE

Namespaces make packages self-contained in two ways: the `imports` and the `exports`. The `imports` defines how a function in one package finds a function in another. The `exports` helps you avoid conflicts with other packages by specifying which functions are available outside of your package (internal functions are available only within your package and can't easily be used by another package). 

* `export()` - export functions (including S3 and S4 generics).
* `exportPattern()` - export all functions that match a pattern
* `exportClasses(), exportMethods()` - export S4 classes and methods
* `S3method()` - export S3 methods

* `import()` - import all functions from a package.
* `importFrom()` - import selected functions (including S4 generics).
* `importClassesFrom(), importMethodsFrom()` - import S4 classes and methods.
* `useDynLib()` - import a function from C

### quick intro

you need the `devtools` and `roxygen2` packages to help creating a package:

```r
    install.packages("devtools")
    library("devtools")
    install.packages("roxygen2")
    library(roxygen2)
```
    
then set the working directory, and create a test `cats` package:

```r
    setwd("your_parent_path")
    usethis::create_package("cats")
```

and create R function files in the `R` package.

then create an document for the package:

```r
    setwd("./cats")
    devtools::document()
```
    
then install your package, you need to run this from the parent working directory that contains the `cats` folder:

```r
    setwd("..")
    devtools::install("cats")
    devtools::install_github('cats','github_username') # put the code to github
```

to remove the installed packages using `uninstall`:

```r
    devtools::uninstall("cats")
```

to bundle the package in an compressed file with extension `.tar.gz`, using

```r
  devtools::build()
  devtools::build(binary=TRUE) # make a binary package
```

`devtools::load_all()` can easily reload the package, or use the shortcut `Ctrl/Cmd + Shift + L`.

### references

* [Writing an R package from scratch](https://hilaryparker.com/2014/04/29/writing-an-r-package-from-scratch/)
* [Hadley](http://r-pkgs.had.co.nz/description.html)
* [roxygen2](https://github.com/klutometis/roxygen#roxygen2)
* [Connecting to other packages](http://kbroman.org/pkg_primer/pages/depends.html)
* [How R Searches and Finds Stuff](http://blog.obeautifulcode.com/R/How-R-Searches-And-Finds-Stuff/)
* [Generating Rd files](https://cran.r-project.org/web/packages/roxygen2/vignettes/rd.html)

