## shiny

### UI

#### layout

* shinyUI
    * fluidPage
        * `title = "app title"`
        * `theme = "app.css(in www directory)"`
        * titlePanel
        * sidebarLayout
            * `position = c("left", "right")`
            * sidebarPanel
            * mainPanel
        * fluidRow
            * column
                * `offset = 1`
                * wellPanel
        * tabsetPanel
            * tabPanel
        * navlistPanel
            * tabPanel
    * navbarPage
        * tabPanel
        * navbarMenu
            * tabPanel
    * fixedPage
        * fixedRow
            * column

* shinyServer(function(input, output){...})
    * input$input_name
    * output$output_name
        
#### widgets

* radioButtons
* selectInput
* checkboxInput
* checkboxGroupInput
* textInput
* helpInput
* numericInput
* sliderInput
    * `ticks = FALSE`
* dateInput
* dateRangeInput
* fileInput
* actionButton
* submitButton - choose to use `actionButton`
* downloadButton


        output$downloadData <- downloadHandler(
            filename = function() {
              paste0("file-", Sys.Date(), ".csv")
              },
            content = function(file) {
              write_excel_csv(dataInput(), file, na = "")
            }
        )
    
#### output and render

* plotOutput -> renderPlot
* imageOutput -> renderImage
* textOutput -> renderText
* htmlOutput -> renderUI
* uiOutput -> renderUI
* verbatimTextOutput
* tableOutput -> renderTable
* DTOutput -> renderDT

#### server functions

* `validate()`
* `reactive()`
* `reactiveValues()`
* `observe()`
* `isolate()`
* `observeEvent()`
* `eventReactive()`

#### html elements

add html elements inside `*Panel` functions. `tags` lists all the tag functions. any HTML tag attributes can be set as an argument inside the tag functions. e.g., `id="id", class="class-name"`

* `p()`
* `h[1-6]()`
* `div()`
* `span()`
* `pre()`
* `code()`
* `a()`
* `img()`
* `strong()`
* `emp()`
* `br()`
* `hr()`
* `HTML()`

### static file

```r
addResourcePath("static", system.file("static", package="presR"))

tags$head(
    tags$link(rel = "stylesheet", type = "text/css", href = "static/css/presr.css")
    )
```

### running

```r
  shinyApp(ui = ui, server = server)
  
  runApp("/app/dir")
```

### reference

* [R Markdown: The Definitive Guide](https://bookdown.org/yihui/rmarkdown/)
* [tutorials](https://shiny.rstudio.com/tutorial/sss)
* [layout](https://shiny.rstudio.com/articles/layout-guide.html)
* [widget values](http://shiny.rstudio.com/gallery/widget-gallery.html)
* [shiny-cheatsheet](https://shiny.rstudio.com/images/shiny-cheatsheet.pdf)
* [shiny examples](https://github.com/rstudio/shiny-examples)
* [modules](https://shiny.rstudio.com/articles/modules.html)
* [shiny css](https://shiny.rstudio.com/articles/css.html)
* [shinydashboard](https://rstudio.github.io/shinydashboard/)
* [bootswatch](https://bootswatch.com/)
* [DT](https://rstudio.github.io/DT/)
* [Using Action Buttons](https://shiny.rstudio.com/articles/action-buttons.html)
* [fontawesome icon](https://fontawesome.com/icons?d=gallery)
