# plotly


```{r setup, message=FALSE}
  library(plotly)
  knitr::opts_chunk$set(warning = FALSE, message = FALSE)

  x <- 1:3
  y <- 5:7
```
## basic charts

1. line

```{r line}
  plot_ly(x=x, y=y, type="scatter", mode="line")
```

2. scatter

```{r scatter}
  plot_ly(x=x, y=y, type="scatter", mode="markers")
```

3. bar

```{r bar}
  plot_ly(x=x, y=y, type="bar")
```

4. bubble

```{r}
  plot_ly(x=x, y=y, type="scatter", mode="markers", marker=list(color = c("red", "blue", "green"), size = c(1, 5, 10)))
```

5. heatmap

```{r heatmap}
  plot_ly(z=volcano, type="heatmap")
```
6. area

```{r area}
  plot_ly(x=x, y=y, type="scatter", mode="line", fill="tozeroy")
```

## statistical charts

1. histogram

```{r hist}
  rhist <- rnorm(100)
  plot_ly(x=rhist, type="histogram")
```

2. boxplot

```{r boxplot}
  plot_ly(x=rhist, type="box")

  plot_ly(y=rhist, type="box")
  
  plot_ly(y=rhist, type="box") %>% add_trace(y=rnorm(100, 1))

```

3. 2d histogram

```{r histogram-2d}
  plot_ly(x=rnorm(100, sd=10), y=rnorm(200, sd=5), type="histogram2d")
```

## maps

1. bubble map

```{r map-bubble}
  plot_ly(type="scattergeo", mode="markers", lon=c(-73.5, 151.2), lat=c(45.5, -33.8), marker=list(color=c("red", "blue"), size=c(30, 50)))
```

2. choropleth map

```{r map-choropleth}
  plot_ly(type="choropleth", locations=c("AZ", "CA", "VT"), locationmode="USA-states", colorscale="Viridis", z=c(10,20,40)) %>% layout(geo=list(scope="usa"))
```

3. scatter map

```{r map-scatter}
  plot_ly(type="scattergeo", lon=c(42, 39), lat=c(12, 22), text=c("Rome", "Greece"), mode="markers")
```

### 3d charts

1. 3d surface

```{r 3d-surface}
  plot_ly(type="surface", z=-volcano)
```

2. 3d line

```{r 3d-line}
  plot_ly(type="scatter3d", x=c(9, 8, 5, 1), y=c(1, 2, 4, 8), z = c(11, 8, 15, 3), mode="line" )
```

3. 3d scatter

```{r 3d-scatter}
  plot_ly(type="scatter3d", x=c(9, 8, 5, 1), y=c(1, 2, 4, 8), z = c(11, 8, 15, 3), mode="markers")
```

## layout

### legends

```{r legend}
  set.seed(123)
  x1 <- 1:100
  y1 <- 2 * x1 + rnorm(100)
  y2 <- -2 * x1 + rnorm(100)
  
  plot_ly(x=x1, y=y1, type="scatter", mode="markers") %>% add_trace(x=x1, y=y2) %>% layout(legend=list(x=0.5, y=1, bgcolor="#F3F3F3"))
```
### axes

```{r axes}
  axis_template <- list(showgrid=FALSE,
                        zeroline=FALSE,
                        nticks=20,
                        showline=TRUE,
                        title="AXIS")

  plot_ly(x=x1, y=y1, type="scatter", mode="markers") %>% layout(xaxis=axis_template, yaxis=axis_template)
```

## references

* [cheetsheet](https://images.plot.ly/plotly-documentation/images/r_cheat_sheet.pdf)
* [github](https://github.com/ropensci/plotly)
* [cookbook](https://plotly-r.com/index.html)
* [plotly~ggplot2](http://ropensci.github.io/plotly/ggplot2/index.html)
* [figure reference](https://plot.ly/r/reference/s)
