- name: create project home for hp
  become: yes
  file:
    path: "{{ proj_home }}"
    mode: 0755
    state: directory
    owner: "{{ remote_user }}"
    group: "{{ remote_user }}"

- name: create base for hp
  file:
    path: "{{ item.value }}"
    state: directory
  loop: "{{ hp_base|dict2items }}"
