hadoop_version: 3.1.2
hadoop_base:
  bin: "{{ hp_base.bin }}/hadoop"
  conf: "{{ hp_base.conf }}/hadoop"
  pid: "{{ hp_base.pid }}/hadoop"
  log: "{{ hp_base.log }}/hadoop"
  data: "{{ hp_base.data }}/hadoop"
  tmp: "{{ hp_base.tmp }}/hadoop"
  name_node: "{{ hp_base.data }}/hadoop/name"
  data_node: "{{ hp_base.data }}/hadoop/data"
  conf_version: "{{ hp_base.conf }}/hadoop/{{ hadoop_version }}"
# core-site.xml
fs_defaultFS_host: "{{ groups['master'][0] }}"
hadoop_tmp_dir: "{{ hadoop_base.tmp }}/tmp"
# hdfs-site.xml
dfs_namenode_name_dir: "{{ hadoop_base.name_node }}"
dfs_datanode_data_dir: "{{ hadoop_base.data_node }}"
dfs_replication: 2
