## write an R package

you can follow these tutorials:

* [Writing an R package from scratch](https://hilaryparker.com/2014/04/29/writing-an-r-package-from-scratch/)
* [Hadley](http://r-pkgs.had.co.nz/description.html)
* [roxygen2](https://github.com/klutometis/roxygen#roxygen2)
* [Connecting to other packages](http://kbroman.org/pkg_primer/pages/depends.html)
* [How R Searches and Finds Stuff](http://blog.obeautifulcode.com/R/How-R-Searches-And-Finds-Stuff/)
* [Generating Rd files](https://cran.r-project.org/web/packages/roxygen2/vignettes/rd.html)

### quick intro

you need the `devtools` and `roxygen2` packages to help creating a package:

    install.packages("devtools")
    library("devtools")
    install.packages("roxygen2")
    or devtools::install_github("klutometis/roxygen2")
    library(roxygen2)
    
then set your working directory, and create a test `cats` package:

    setwd("your_parent_path")
    create("cats")

and create R function files in the `R` package.

then create an document for your package:

    setwd("./cats")
    document()
    
then install your package, you need to run this from the parent working directory that contains the `cats` folder:

    setwd("..")
    install("cats")

you can remove the installed packages using `uninstall`:

    uninstall("cats")
