- name: create java bin home directory
  file:
    path: "{{ java_bin_home }}"
    state: directory

- name: rsync jdk source file to remote server
  synchronize:
    src: "{{ jdk_source_name }}"
    dest: "{{ java_bin_home }}"

- name: configure jave environment variables
  blockinfile:
    path: "{{ hp_bashrc }}"
    create: yes
    marker: "# {mark} java configuration"
    block: |
      export JAVA_HOME={{ java_home }}
      export PATH=${JAVA_HOME}/bin:${PATH}
